/-
Machine-checks the audit surface: the statement of the headline theorem must
unfold only to constants defined under `Esa22Copy/Model/`.

This is tooling, hence proof content, hence deliberately *outside* the surface
it checks.

Seeding from a theorem's **type** rather than its value is the crux: the proof
may use anything, and routinely should. Only the statement is constrained.
-/
import Lean

open Lean Elab Command

namespace Esa22Copy.Meta

/-- All `Esa22Copy` constants reachable from a seed, through both types and values. -/
private partial def closureAux (env : Environment) :
    NameSet → List Name → NameSet → NameSet
  | _, [], acc => acc
  | seen, c :: rest, acc =>
    if seen.contains c then closureAux env seen rest acc
    else
      let seen := seen.insert c
      let acc := if (`Esa22Copy).isPrefixOf c then acc.insert c else acc
      match env.find? c with
      | none => closureAux env seen rest acc
      | some ci =>
        let next := ci.type.getUsedConstants.toList
          ++ (match ci.value? with | some v => v.getUsedConstants.toList | none => [])
        closureAux env seen (next ++ rest) acc

/-- Which module defines a constant.

    `getModuleIdxFor?` is the only route in current Lean: `getModuleFor?` was
    removed, and an index has to be looked up in the header's module table. A
    constant with no index is not imported at all — it belongs to the module
    being elaborated right now. -/
private def moduleOf (env : Environment) (c : Name) : Name :=
  match env.getModuleIdxFor? c with
  | some idx => (env.allImportedModuleNames[idx.toNat]?).getD `«unknown»
  | none => env.mainModule

/-- **Modules a statement may unfold into besides `Model/`.**

`Arlib.Computation` supplies the currency a cost is counted in — `StdOp`, `Cell`,
`StdImpl` — so a running-time or space statement necessarily mentions it.  Before
that, this development declared its own currency and this list was empty.

Admitting it is a real widening: an `Arlib.Computation` constant in a headline
statement is trusted without being read here.  What backs it is that arlib is a
library with its own seal and its own audit — `arlib/scripts/ComputationAudit.lean`
over 511 declarations — rather than this development's proof scratch, and that the
alternative was an eleven-constructor translation table a reader had to check by
eye for no gain.

It is deliberately not `Arlib`: only the computation area, and only because a
cost claim has to name the unit it is in. -/
private def admittedOutsideModel : List Name :=
  [`Arlib.Computation]

/-- Constants defined neither under `Esa22Copy/Model/` nor in an admitted module,
paired with the module defining them. -/
private def outsideModel (env : Environment) (cls : NameSet) : List (Name × Name) :=
  cls.toList.filterMap fun c =>
    let mod := moduleOf env c
    if (`Esa22Copy.Model).isPrefixOf mod then none
    else if admittedOutsideModel.any (·.isPrefixOf mod) then none
    else some (c, mod)

/-- Seeded from a definition's own body — use this on the algorithm. -/
elab "#modelClosure " id:ident : command => do
  let env ← getEnv
  let n ← liftCoreM <| Lean.realizeGlobalConstNoOverload id
  let cls := (closureAux env {} [n] {}).erase n
  match outsideModel env cls with
  | [] => logInfo m!"OK — closure of {n} is under Model/ or Arlib.Computation ({cls.toList.length})"
  | bad => throwError m!"OUTSIDE Model/ in closure of {n}: {bad}"

/-- Names the elaborator generates for every declaration, which nobody wrote and
which therefore cannot be moved out of `Model/`. -/
private def autoGenerated : List String :=
  ["noConfusion", "noConfusionType", "casesOn", "recOn", "rec", "brecOn", "below",
   "ndrec", "injEq", "inj", "sizeOf_spec", "mk", "toCtorIdx", "ofNat", "eq_def",
   "elim", "ctorIdx", "ctorElim", "ctorElimType", "ofNat_ctorIdx", "eq_1", "repr",
   "default"]

private def isAutoGenerated (c : Name) : Bool :=
  -- `inst` can appear at any depth (`instReprFoo.repr.match_1`), and the
  -- elaborator numbers its match auxiliaries, so neither test can look only at
  -- the last component or only at a fixed list
  c.components.any (fun p => match p with
    | .str _ s => "inst".isPrefixOf s || "match_".isPrefixOf s
    | _ => false)
  || (match c.componentsRev.headD .anonymous with
      | .str _ s => autoGenerated.contains s
      | _ => false)

/-- **A module holds exactly what its claims are about, and nothing else.**

`#surplusIn M from s₁ … sₙ` reports every author-written constant *defined* in a
module under `M` that the seeds do not reach.  A seed that is a theorem
contributes its statement; a seed that is a definition contributes itself.

The closure checks say nothing in a statement escapes `Model/`.  This says
nothing in a module escapes its own claims, and the pair together pin the audited
surface from both sides.  Without it a module only ever grows: a definition
parked there for convenience is indistinguishable, to a reader, from one the
claims depend on, and the surface a human is asked to read silently widens.

**Instances defined in the module are seeds too.**  An instance is part of how
the module is written rather than something parked in it — the four naming tables
of `Model/Program.lean` are exactly this, and so is a currency's own `Fintype`,
whose witness list would otherwise report as surplus.  Nothing can hide there:
an instance is a term of a class, so a definition that is not one cannot be
smuggled inside it.

Surplus is a **warning**, not a build error, because whether a surplus definition
should move or the claims should mention it is a judgment.  What is not a
judgment is knowing which ones they are. -/
elab "#surplusIn " mod:ident " from " ids:ident+ : command => do
  let env ← getEnv
  let prefix_ := mod.getId
  let mut seeds : List Name := []
  let mut named : List Name := []
  for id in ids do
    let n ← liftCoreM <| Lean.realizeGlobalConstNoOverload id
    let some ci := env.find? n | throwError "unknown constant {n}"
    named := n :: named
    -- a theorem contributes its statement; a definition contributes itself
    let isP ← liftTermElabM (Lean.Meta.isProp ci.type)
    seeds := seeds ++ (if isP then ci.type.getUsedConstants.toList else [n])
  -- every instance the module declares is a seed: see the docstring
  for (c, _) in env.constants.toList do
    if c.isInternal then continue
    unless prefix_.isPrefixOf (moduleOf env c) do continue
    if ← liftTermElabM (Lean.Meta.isInstance c) then seeds := seeds ++ [c]
  -- a seed is reached by itself: a theorem does not appear in its own statement
  let mut keep := closureAux env {} seeds {}
  for n in named do keep := keep.insert n
  let mut surplus : Array Name := #[]
  for (c, _) in env.constants.toList do
    if c.isInternal || isAutoGenerated c then continue
    unless (`Esa22Copy).isPrefixOf c do continue
    unless prefix_.isPrefixOf (moduleOf env c) do continue
    if keep.contains c then continue
    -- a field of a structure the claims reach is reached: the field is part of
    -- that structure, not a separate thing parked in the module
    if let some pi := env.getProjectionFnInfo? c then
      if keep.contains pi.ctorName.getPrefix then continue
    surplus := surplus.push c
  if surplus.isEmpty then
    logInfo m!"OK — every author-written constant under {prefix_} is reached by \
      its claims ({keep.toList.length} reached)."
  else
    logWarning m!"SURPLUS in {prefix_} — defined there, reached by none of its \
      claims, so it widens the audited surface without widening the claim: \
      {surplus.toList}"

/-- Seeded from a theorem's *type*, so the statement — not the proof — unfolds. -/
elab "#modelClosureOfType " id:ident : command => do
  let env ← getEnv
  let some ci := env.find? (← liftCoreM <| Lean.realizeGlobalConstNoOverload id)
    | throwError "unknown constant"
  let cls := closureAux env {} ci.type.getUsedConstants.toList {}
  match outsideModel env cls with
  | [] => logInfo m!"OK — the STATEMENT is under Model/ or Arlib.Computation ({cls.toList.length})"
  | bad => throwError m!"OUTSIDE Model/ in the statement: {bad}"

end Esa22Copy.Meta
